### ISSUE TITLE
how to register HMO patients

### ISSUE THREAD

**Issue by danceasarxx** [danceasarxx/darya#1]
The current [patient registeration form](https://beta.hospitalrun.io/#/patients/edit/new) does not have the ability to select HMO type. There should be a field that on the registration form for selecting HMO type. On selecting this the user should see another list of all the accredited HMOS so he/she can select the patient's HMO
[HMO Contacts.pdf](https://github.com/danceasarxx/hospitalrun-frontend/files/913119/HMO.Contacts.pdf)

**Comment by waleplanet** [comment]
@tangollama add hmo field to  new patient form
![screenshot from 2017-04-26 23-05-37](https://cloud.githubusercontent.com/assets/9745471/25459184/f498a7c4-2ad4-11e7-9258-1d6659578788.png)
